FORMAT: 1A
HOST: LoLDatabaseAPI

# LoLDatabaseAPI

LoLDatabaseAPI is a simple and friendly to use API allowing the League of Legends developer community to access to all League of Legend game data in the most convenient way possible.

## Get All Champions [/champions]

### /champions [GET]

Fetches info for all champions

+ Response 200 (application/json)

        "example": [
            {
                "id": "Aatrox",
                "lore": "Tell me again, ...",
                "championsStats": [
                    "health": 1234,
                    "attackDamage": 341,
                    ...
                ]
                "recommended" : 
                    "items": [
                        {
                            "count": 1,
                            "id": "Duskbalde"
                        },
                        {
                            "count": 1,
                            "id": "BoTRK"
                        },
                        {
                            "count": 3,
                            "id": "Potions"
                        }
                    ],
                "Lore": "..."
                "GameModes": {
                    "Normals": true,
                    "Ranked": true,
                    "ARAM": true,
                }
            },
            {
                "id": "4293472123",
                "recommended" : 
                    "items": [
                        {
                            "count": 1,
                            "id": "Duskbalde"
                        },
                        {
                            "count": 1,
                            "id": "BoTRK"
                        },
                        {
                            "count": 3,
                            "id": "Potions"
                        }
                    ],
                "Lore": "..."
                "GameModes": [
                    "Normals": true,
                    "Ranked": true,
                    "ARAM": true,
                ]
            },
            {
                "etc.." : info
            }
        ]

+ Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }

## Get Specific Champion [/champions/{champion}]

### /champions/{champion} [GET]

Fetches info for a specific champion

+ Parameters
    + champion (string, required)  - champion name in all lower case no spaces


+ Response 200 (application/json)

        "example": [
            {
                "id": "Aatrox",
                "recommended" : 
                    "items": [
                        {
                            "count": 1,
                            "name": "BoTRK"
                        },
                        {
                            "count": 1,
                            "id": "Duskblade"
                        },
                        {
                            "count": 3,
                            "id": "Potions"
                        }
                    ],
                "Lore" : "..."
                "GameModes": {
                    "Normals": true,
                    "Ranked": true,
                    "ARAM": true,
                    "StarGaurdian": false
                }
            }
        ]

+ Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }
        
## Get All Items [/items]

### /items [GET]

Fetches info for items

+ Response 200 (application/json)

        "example": [
            "Morellonomicon": {
                "frequentlyBuiltOn": [
                    "Karma",
                    "Annie
                ],
                "Maps": {
                    "SummonersRift": true,
                    "HowlingAbyss": true,
                    "TheDarkStarRises": false
                },
                "description": "<stats>+100 Ability Power<br><mana>+400 Mana</mana></stats><br><br><unique>UNIQUE Passive:</unique> +20% Cooldown Reduction<br><unique>UNIQUE Passive:</unique> Dealing magic damage to champions below 35% Health inflicts <a href='GrievousWounds'>Grievous Wounds</a> for 8 seconds.<br><unique>UNIQUE Passive:</unique> Kills and Assists restore 20% of your maximum Mana.",
                "plaintext": "Greatly increases Ability Power and Cooldown Reduction",
                "sanitizedDescription": "+100 Ability Power +400 Mana UNIQUE Passive: +20% Cooldown Reduction UNIQUE Passive: Dealing magic damage to champions below 35% Health inflicts Grievous Wounds for 8 seconds. UNIQUE Passive: Kills and Assists restore 20% of your maximum Mana.",
                "id": 3165,
                "itemTree": [
                    "FiendishCodex",
                    "AmplifyingTone",
                    "LostChapter"
                ]  
                "name": "Morellonomicon"
            },
            "Moonflair Spellblade": {
                "frequentlyBuiltOn": [
                    "Riven",
                    "Malphite"
                ],
                "Maps": {
                    "SummonersRift": true,
                    "HowlingAbyss": true,
                    "TheDarkStarRises": false
                },
                "description": "<stats>+50 Ability Power<br>+50 Armor<br>+50 Magic Resist</stats><br><br><unique>UNIQUE Passive - Tenacity:</unique> Reduces the duration of stuns, slows, taunts, fears, silences, blinds, polymorphs, and immobilizes by 35%.",
                "sanitizedDescription": "+50 Ability Power +50 Armor +50 Magic Resist UNIQUE Passive - Tenacity: Reduces the duration of stuns, slows, taunts, fears, silences, blinds, polymorphs, and immobilizes by 35%.",
                "id": 3170,
                "itemTree": [
                    "SeekersArmguard",
                    "NegatronCloak"
                ]  
                "name": "Moonflair Spellblade"
            }, {
                "etc....": "iteminfo"
            }
        ]
 
+ Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }
 
        
## Get a Specific Item [/items/{item}]

### /items/{item} [GET]

Fetches info for a specific item

+ Parameter
    + item - item name with no spaces and lowercase
    
+ Response 200 (application/json)

        "example" : [
            "Morellonomicon": {
                "frequentlyBuiltOn": [
                    "ID": "Karma",
                    "ID": "Annie"
                ],
                "Maps": {
                    "SummonersRift": true,
                    "HowlingAbyss": true,
                    "TwistedTreeline": true
                },
                "description": "<stats>+100 Ability Power<br><mana>+400 Mana</mana></stats><br><br><unique>UNIQUE Passive:</unique> +20% Cooldown Reduction<br><unique>UNIQUE Passive:</unique> Dealing magic damage to champions below 35% Health inflicts <a href='GrievousWounds'>Grievous Wounds</a> for 8 seconds.<br><unique>UNIQUE Passive:</unique> Kills and Assists restore 20% of your maximum Mana.",
                "plaintext": "Greatly increases Ability Power and Cooldown Reduction",
                "sanitizedDescription": "+100 Ability Power +400 Mana UNIQUE Passive: +20% Cooldown Reduction UNIQUE Passive: Dealing magic damage to champions below 35% Health inflicts Grievous Wounds for 8 seconds. UNIQUE Passive: Kills and Assists restore 20% of your maximum Mana.",
                "id": 3165,
                "itemTree": [
                    "FiendishCodex",
                    "AmplifyingTone",
                    "LostChapter"
                ] 
                "name": "Morellonomicon"
            }
        ]


+ Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }

## Get Game Mode [/gameModes/{gameMode}]
    
### /gameModes/{gameMode} [GET]

Fetches info for a game mode

+ Parameter
    + gameMode (number, required) - String game mode all lower case, using dashes instead of space
        1. Summoner's Rift
        2. Howling Abyss
        3. Twisted Treeline
    
+ Response 200 (applicaton/json)
    
        "example": [
            "Summoners Rift": {
                "MapImg": "http://url.png"
                "Lore": "will populate with real lore",
                "InGameDescription": "The newest and most...",
                "Versions": [
                    "Summer Version": "It's the first...",
                    "Winter Version": "A variant of the..."
                ],
                "Development": "Summoner Rift evolves...",
                "Playable Champions": [
                    "Lux",
                    "Aatrox",
                    "Caitlyn",
                    "etc."
                ],
                "Items": [
                    "Duskblade",
                    "BoTRK",
                    "etc."
                ]
            }
        ]
        
+ Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }
        
## Summoner's Match History [/summoner/matchHistory/{summonerName}]

### /summoner/matchHistory/{summonerName} [GET]

Fetches recent match history for a summoner

+ Parameter 
    + summonerName - fetch match history for this specific summoner
    
+ Response 200 (application/json)
    
        "matches" : [
            {
                "lane": "MID",
                "champion": "Annie",
                "MatchID": 218533808,
                "Map": "HowlingAbyss",
                "GameMode": "ARAM",
                "Items": [
                    {
                        "ID": "Doran's Ring",
                        "Count": 1
                    }, 
                    {
                        "ID": "Luden's Echo",
                        "Count": 1
                    },
                    {
                        "ID": "Redemption",
                        "Count": 1
                    }
                ]
            },
            {
                "lane": "JUNGLE",
                "champion": "Hecarim",
                "MatchID": 4819434182,
                "Map": "HowlingAbyss",
                "GameMode": "ARAM",
                "Items": [
                    {
                        "ID": "Cinderhulk",
                        "count": 1
                    },    
                    {
                        "ID": "Warmog's Armor",
                        "count": 1
                    }, 
                    {
                        "ID": "Yap Yap Item",
                        "count": 1
                    }
                ]
            },
            {
                "etc...", 1234
            }
        ]

+ Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }

## Match Details [/matches/matchHistory/{matchID}]

### /matches/matchHistory/{matchID} [GET]

Fetches details about a specific match.

+ Parameter
    + matchID (number) - ID of the match you are looking up

+ Response 200 (application/json)
    
        "example": [
            "matchDetails": {
                "MatchID: 4819434182,
                "Participants": {
                    "Participant1": {
                        "champion": "Annie",
                        "summonerID": 4819434182,
                        "Items": [
                            {
                                "ID": "Doran's Ring",
                                "count": 1
                            },
                            {
                                "ID": "Manamune",
                                "count": 1
                            },
                            {
                                "ID": "Zhonya's Hourglass",
                                "count": 1
                            }
                        ]
                    },
                    "Participant2": {
                        "etc....." : "adsfasd"
                    },
                    ...
                },
                "Map": "Summoner's Rift",
                "Game Mode": "ARAM",
                "TimeLength": 30:21,
                "Winning Team": "Blue",
                "MatchDetails: [
                    ...
                ]
            }
        ]
        
+ Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }