FORMAT: 1A
HOST: LoLDatabaseAPI

# LoLDatabaseAPI

LoLDatabaseAPI is a simple and friendly to use API allowing the League of Legends developer community to access to all League of Legend game data in the most convenient way possible.

## Champions [/champions]

**Champion DTO:**

*id(long)*: an identifying key for champions

*lore(string)*: background info on that champion

*championStats(statDTO)*: provides starting stat info on champion

*recommended(List[ItemID])*: provides recommended item build for champion

*gameModes(List[boolean])*: provides a list of gameModes this champion is available on
 



### Get All Champions [GET]

*Description: Fetches a list of Champion DTO's (List[ChampionDTO's])*

+ Response 200 (application/json)

        "example": {
            "Riven": {
                "id": "1234544321",
                "championsStats": [
                    "health": 1234,
                    "attackDamage": 341,
                    ...
                ]
                "recommended" : 
                    "items": [
                        {
                            "count": 1,
                            "id": "Duskbalde"
                        },
                        {
                            "count": 1,
                            "id": "BoTRK"
                        },
                        {
                            "count": 3,
                            "id": "Potions"
                        }
                    ],
                "Lore": "..."
                "GameModes": {
                    "Normals": true,
                    "Ranked": true,
                    "ARAM": true,
                }
            },
            "Urgot": {
                "id": "4293472123",
                "championsStats": [
                    "health": 1234,
                    "attackDamage": 341,
                    ...
                ]
                "recommended" : 
                    "items": [
                        {
                            "count": 1,
                            "id": "Duskbalde"
                        },
                        {
                            "count": 1,
                            "id": "BoTRK"
                        },
                        {
                            "count": 3,
                            "id": "Potions"
                        }
                    ],
                "Lore": "..."
                "GameModes": [
                    "Normals": true,
                    "Ranked": true,
                    "ARAM": true,
                ]
            },
            {
                "etc.." : info
            }
        }

+ Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }

### Get Specific Champion [GET /champions/{championID}]

*Description: Fetches ChampionDTO for a specific champion.*

+ Parameters
    + championID (string, required)  - champion name in all lower case no spaces


+ Response 200 (application/json)

        "example": {
            "Riven": {
                "id": "1234452134",
                "recommended" : 
                    "items": [
                        {
                            "count": 1,
                            "name": "BoTRK"
                        },
                        {
                            "count": 1,
                            "id": "Duskblade"
                        },
                        {
                            "count": 3,
                            "id": "Potions"
                        }
                    ],
                "championsStats": [
                    "health": 1234,
                    "attackDamage": 341,
                    ...
                ]
                "Lore" : "..."
                "GameModes": {
                    "Normals": true,
                    "Ranked": true,
                    "ARAM": true,
                    "StarGaurdian": false
                }
            }
        }

+ Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }
        
## Items [/items]

**Item DTO**

*frequentlyBuiltOn(List[string])*: List of champions who frequently build this item

*maps(List[boolean])*: List of maps this item is available on

*description(string)*: Description of item stats

*plainText(string)*: Description of this item

*sanitizedDescription(string)*: Description of stat buff and passive

*itemTree(List[strings])*: List of children items required to build this item

*name(string)*: item name/identifier

*id(long)*: item identifier (might make string???)

### Get All Items [GET]

*Description: Fetches info for all items. Returns a List[ItemDTO]*


+ Response 200 (application/json)

        "example": [
            "Morellonomicon": {
                "frequentlyBuiltOn": [
                    "Karma",
                    "Annie
                ],
                "Maps": {
                    "SummonersRift": true,
                    "HowlingAbyss": true,
                    "TheDarkStarRises": false
                },
                "description": "<stats>+100 Ability Power<br><mana>+400 Mana</mana></stats><br><br><unique>UNIQUE Passive:</unique> +20% Cooldown Reduction<br><unique>UNIQUE Passive:</unique> Dealing magic damage to champions below 35% Health inflicts <a href='GrievousWounds'>Grievous Wounds</a> for 8 seconds.<br><unique>UNIQUE Passive:</unique> Kills and Assists restore 20% of your maximum Mana.",
                "plaintext": "Greatly increases Ability Power and Cooldown Reduction",
                "sanitizedDescription": "+100 Ability Power +400 Mana UNIQUE Passive: +20% Cooldown Reduction UNIQUE Passive: Dealing magic damage to champions below 35% Health inflicts Grievous Wounds for 8 seconds. UNIQUE Passive: Kills and Assists restore 20% of your maximum Mana.",
                "id": 3165,
                "itemTree": [
                    "FiendishCodex",
                    "AmplifyingTone",
                    "LostChapter"
                ]  
                "name": "Morellonomicon",
                "id": 12345423134
            },
            "Moonflair Spellblade": {
                "frequentlyBuiltOn": [
                    "Riven",
                    "Malphite"
                ],
                "Maps": {
                    "SummonersRift": true,
                    "HowlingAbyss": true,
                    "TheDarkStarRises": false
                },
                "description": "<stats>+50 Ability Power<br>+50 Armor<br>+50 Magic Resist</stats><br><br><unique>UNIQUE Passive - Tenacity:</unique> Reduces the duration of stuns, slows, taunts, fears, silences, blinds, polymorphs, and immobilizes by 35%.",
                "sanitizedDescription": "+50 Ability Power +50 Armor +50 Magic Resist UNIQUE Passive - Tenacity: Reduces the duration of stuns, slows, taunts, fears, silences, blinds, polymorphs, and immobilizes by 35%.",
                "id": 3170,
                "itemTree": [
                    "SeekersArmguard",
                    "NegatronCloak"
                ]  
                "name": "Moonflair Spellblade",
                "id": 415324124
            }, {
                "etc....": "iteminfo"
            }
        ]
 
+ Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }

### Get Specific Item [GET /items/{item}]

*Description: Fetches an ItemDTO for a specific item*



+ Parameter
    + item - item name with no spaces and lowercase
    
+ Response 200 (application/json)

        "example" : [
            "Morellonomicon": {
                "frequentlyBuiltOn": [
                    "ID": "Karma",
                    "ID": "Annie"
                ],
                "Maps": {
                    "SummonersRift": true,
                    "HowlingAbyss": true,
                    "TwistedTreeline": true
                },
                "description": "<stats>+100 Ability Power<br><mana>+400 Mana</mana></stats><br><br><unique>UNIQUE Passive:</unique> +20% Cooldown Reduction<br><unique>UNIQUE Passive:</unique> Dealing magic damage to champions below 35% Health inflicts <a href='GrievousWounds'>Grievous Wounds</a> for 8 seconds.<br><unique>UNIQUE Passive:</unique> Kills and Assists restore 20% of your maximum Mana.",
                "plaintext": "Greatly increases Ability Power and Cooldown Reduction",
                "sanitizedDescription": "+100 Ability Power +400 Mana UNIQUE Passive: +20% Cooldown Reduction UNIQUE Passive: Dealing magic damage to champions below 35% Health inflicts Grievous Wounds for 8 seconds. UNIQUE Passive: Kills and Assists restore 20% of your maximum Mana.",
                "id": 3165,
                "itemTree": [
                    "FiendishCodex",
                    "AmplifyingTone",
                    "LostChapter"
                ] 
                "name": "Morellonomicon",
                "id": 127431232
            }
        ]


+ Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }

## Get Game Mode [/gameModes]
    
**GameModeDTO**

*GameModeID(int)*: key for this game mode (unsure if it will remain int or string)

*mapImg(url)*: a url to image of game mode map

*lore(string)*: lore behind the game mode

*InGameDesciprtion(string)*: description of the in game play for this game mode

*Versions(List[string])*: returns the different types of maps

*PlayableChampions(List[championIDs])*: returns a list of champions you can use on this game mode

*Items(list[ItemID's])*: returns a list of items usable in this game mode

### Get Game Mode Description with Game Mode ID [GET /gameModes/{gameMode}]

*Description: Fetches list of GameModeDTO's for a game mode*


+ Parameter
    + gameMode (number, required) - String game mode all lower case, using dashes instead of space
        1. Summoner's Rift
        2. Howling Abyss
        3. Twisted Treeline
    
+ Response 200 (applicaton/json)
    
        "example": [
            "Summoners Rift": {
                "GameModeID": 1
                "MapImg": "http://url.png"
                "Lore": "will populate with real lore",
                "InGameDescription": "The newest and most...",
                "Versions": [
                    "Summer Version": "It's the first...",
                    "Winter Version": "A variant of the..."
                ],
                "Development": "Summoner Rift evolves...",
                "Playable Champions": [
                    "Lux",
                    "Aatrox",
                    "Caitlyn",
                    "etc."
                ],
                "Items": [
                    "Duskblade",
                    "BoTRK",
                    "etc."
                ]
            }
        ]
        
+ Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }
        
## Summoner's Match History [/summoner/matchHistory]

**MatcheHistoryForSummonerDTO**

*land(string or laneID)*: returns the lane this champion played

*matchID(long)*: unique match id 

*map(mapID)*: mapid of map this match was played on

*gameModeID(gameModeID)*: Game mode identifier

*Items(List[itemID])*: returns a list of items this champion bought in this match



### Get a Summoner's Match History With Summoner ID [GET /summoner/matchHistory/{summonerName}]

*Description: Fetches a list of MatchHistoryForSummonerDTO's*


+ Parameter 
    + summonerName - fetch match history for this specific summoner
    
+ Response 200 (application/json)
    
        "matches" : [
            {
                "lane": "MID",
                "champion": "Annie",
                "MatchID": 218533808,
                "Map": "HowlingAbyss",
                "GameMode": "ARAM",
                "Items": [
                    {
                        "ID": "Doran's Ring",
                        "Count": 1
                    }, 
                    {
                        "ID": "Luden's Echo",
                        "Count": 1
                    },
                    {
                        "ID": "Redemption",
                        "Count": 1
                    }
                ]
            },
            {
                "lane": "JUNGLE",
                "champion": "Hecarim",
                "MatchID": 4819434182,
                "Map": "HowlingAbyss",
                "GameMode": "ARAM",
                "Items": [
                    {
                        "ID": "Cinderhulk",
                        "count": 1
                    },    
                    {
                        "ID": "Warmog's Armor",
                        "count": 1
                    }, 
                    {
                        "ID": "Yap Yap Item",
                        "count": 1
                    }
                ]
            },
            {
                "etc...", 1234
            }
        ]

+ Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }

## Match Details [/matches/matchHistory/]

**MatchDTO**

*MatchID(long)*: unique number for this match

*Participants(List[ParticipantDTO's])*: returns list of participant dto's for this match

*map(mapID)*: Identifier for the map this match was played on

*gameModeID(gameModeID)*: Identifier for the type of game mode

*matchDetails(MatchDetailDTO)*: will include things like match length, winning team, etc.

### Get Match Details With Match ID [GET /matches/matchHistory/{matchID}]

*Description: Fetches MatchDTO for a specific match.*

+ Parameter
    + matchID (number) - ID of the match you are looking up

+ Response 200 (application/json)
    
        "example": [
            "matchDetails": {
                "MatchID: 4819434182,
                "Participants": {
                    "Participant1": {
                        "champion": "Annie",
                        "summonerID": 4819434182,
                        "Items": [
                            {
                                "ID": "Doran's Ring",
                                "count": 1
                            },
                            {
                                "ID": "Manamune",
                                "count": 1
                            },
                            {
                                "ID": "Zhonya's Hourglass",
                                "count": 1
                            }
                        ]
                    },
                    "Participant2": {
                        "etc....." : "adsfasd"
                    },
                    ...
                },
                "Map": "Summoner's Rift",
                "Game Mode": "ARAM",
                "MatchDetails: [
                    "TimeLength": 30:21,
                    "Winning Team": "Blue",
                    ...
                ]
            }
        ]
        
+ Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }